main: com.cavetale.worldmarker.WorldMarkerPlugin
name: WorldMarker
version: 0.1
api-version: 1.18
description: Manage custom persistent ids in blocks, items, entities.
author: StarTux
website: https://cavetale.com
depend: []
softdepend: []
commands:
  worldmarker:
    aliases: []
    description: WorldMarker Command
    permission: worldmarker.worldmarker
    usage: |-
      /worldmarker block get
      /worldmarker block set <id>
      /worldmarker block reset
      /worldmarker block list
      /worldmarker block debug
      /worldmarker entity get
      /worldmarker entity set <id>
      /worldmarker entity reset
      /worldmarker item [id] - Get or set item id
permissions:
  worldmarker.worldmarker:
    description: Use /worldmarker
    default: op
